### ISSUE TITLE
No files matching the pattern "src" were found

### ISSUE THREAD

**Issue by brobertsUPS** [iCrawl/action-eslint#141]
Thanks for the project! I started running into the following error after the latest update:

```
Added matchers: 'eslint-stylish'. Problem matchers scan action output for known warning or error strings and report these inline.
/opt/hostedtoolcache/node/12.14.1/x64/bin/node /home/runner/work/calm/calm/node_modules/eslint/bin/eslint --ext js,jsx,ts,tsx src
Oops! Something went wrong! :(
ESLint: 6.7.2.
No files matching the pattern "src" were found.
Please check for typing mistakes in the pattern.
##[error]Node run failed with exit code 1
```

I took a look at eslint-stylish to see if that might be the cause but nothing stood out to me. I think the eslint command with the `src` at the end is most likely the culprit.

Here is my `lint.yml` file:

```
name: ESLint

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: Lint updated files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: eslint
        uses: icrawl/action-eslint@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          job-name: eslint
          default-dir: '.'
```

Setting it back to `uses: icrawl/action-eslint@v1.8.0` made eslint run again for me.
